import {
  AppWindow,
  Gauge,
  ServerCog,
  Database,
  ClipboardList,
  Handshake,
} from 'lucide-react';

export const SKILL_CATEGORIES = [
  {
    id: 'realiser',
    icon: <AppWindow size={28} />,
    title: 'Réaliser',
    subtitle: 'Développement',
    description: 'Conception et réalisation d\'applications web et mobiles',
    tagline: 'BUILD & CREATE',
    languages: ['HTML5', 'CSS3', 'JavaScript', 'TypeScript', 'Java', 'PHP'],
    frameworks: ['React', 'Next.js', 'Vue.js', 'Flutter', 'Node.js'],
    tools: ['VS Code', 'IntelliJ', 'Android Studio'],
    color: '#8f7aff',
    gradient: 'linear-gradient(135deg, #8f7aff 0%, #6366f1 100%)',
  },
  {
    id: 'optimiser',
    icon: <Gauge size={28} />,
    title: 'Optimiser',
    subtitle: 'Performance',
    description: 'Optimisation des performances et algorithmique avancée',
    tagline: 'PERFORMANCE',
    languages: ['C', 'C++'],
    frameworks: ['Algorithmique Avancée'],
    tools: ['SonarQube', 'Lighthouse', 'Profilers'],
    color: '#ffd93d',
    gradient: 'linear-gradient(135deg, #ffd93d 0%, #f59e0b 100%)',
  },
  {
    id: 'administrer',
    icon: <ServerCog size={28} />,
    title: 'Administrer',
    subtitle: 'Infrastructure',
    description: 'Gestion et administration de systèmes et réseaux',
    tagline: 'INFRASTRUCTURE',
    languages: ['Bash', 'PowerShell'],
    frameworks: [],
    tools: ['Linux (Debian/Ubuntu)', 'Windows Server', 'Cisco Packet Tracer', 'pfSense', 'VirtualBox'],
    color: '#00d4ff',
    gradient: 'linear-gradient(135deg, #00d4ff 0%, #0ea5e9 100%)',
  },
  {
    id: 'gerer',
    icon: <Database size={28} />,
    title: 'Gérer',
    subtitle: 'Données',
    description: 'Gestion de bases de données et administration de données',
    tagline: 'DATA MANAGEMENT',
    languages: ['SQL', 'PL/SQL', 'Python (Data)'],
    frameworks: [],
    tools: ['MySQL', 'PostgreSQL', 'MongoDB', 'Merise', 'RGPD'],
    color: '#ff6b6b',
    gradient: 'linear-gradient(135deg, #ff6b6b 0%, #f43f5e 100%)',
  },
  {
    id: 'conduire',
    icon: <ClipboardList size={28} />,
    title: 'Conduire',
    subtitle: 'Gestion de projet',
    description: 'Conduite de projets et méthodes agiles',
    tagline: 'PROJECT LEADING',
    languages: [],
    frameworks: ['Agile', 'Scrum', 'Kanban'],
    tools: ['Jira', 'Trello', 'GitHub Projects', 'Gantt'],
    color: '#a855f7',
    gradient: 'linear-gradient(135deg, #a855f7 0%, #7c3aed 100%)',
  },
  {
    id: 'collaborer',
    icon: <Handshake size={28} />,
    title: 'Collaborer',
    subtitle: 'Travail d\'équipe',
    description: 'Communication et collaboration en équipe',
    tagline: 'TEAMWORK',
    languages: ['Français (Natif)', 'Anglais (B2/C1)'],
    frameworks: [],
    tools: ['Slack', 'Discord', 'Teams', 'Zoom'],
    color: '#ec4899',
    gradient: 'linear-gradient(135deg, #ec4899 0%, #db2777 100%)',
  },
] as const;

export const getTransform3D = (mousePosition: { x: number; y: number }): string => {
  const rotateX = (mousePosition.y - 0.5) * -10;
  const rotateY = (mousePosition.x - 0.5) * 10;
  return `perspective(1000px) rotateX(${rotateX}deg) rotateY(${rotateY}deg)`;
};
